package com.usa.attendancesystem.dto;

import java.time.LocalDate;
import java.util.Set;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * DTO for the request to create a new student.
 */
public record CreateStudentRequest(
        // Student ID code is now generated by the backend based on batch
        String studentIdCode,
        
        @NotBlank(message = "Index number is required")
        @Size(max = 10)
        String indexNumber,
        
        @NotBlank(message = "Full name is required")
        @Size(max = 255)
        String fullName,
        
        @NotBlank(message = "Address is required")
        @Size(max = 500)
        String address,
        
        @Size(max = 15)
        String nic, // Optional
        
        @NotBlank(message = "School is required")
        @Size(max = 255)
        String school,
        
        @NotBlank(message = "Parent phone number is required")
        @Size(max = 20)
        String parentPhone,
        
        @NotNull(message = "Admission date is required")
        LocalDate admissionDate,

        @NotNull(message = "Batch ID is required")
        Integer batchId,
        
        @NotEmpty(message = "At least one subject ID is required")
        Set<Integer> subjectIds
        ) {

}
